import { Injectable } from '@nestjs/common';
import type {
  PlaceProvider,
  PlaceSearchRequest,
  PlaceSearchResponse,
  ProviderPlaceRecord,
} from './place-provider';

const FIXTURES: ProviderPlaceRecord[] = [
  {
    provider: 'mock-place',
    providerMode: 'mock',
    sourcePlaceId: 'mock-seongsu-cafe-1',
    sourcePlaceIdKind: 'provider',
    name: '[MOCK] 静かなカフェ',
    rawCategory: '카페,디저트>카페',
    address: '서울특별시 성동구 성수동1가',
    roadAddress: '서울특별시 성동구 서울숲길 1',
    longitude: 127.0436,
    latitude: 37.5467,
    rawPayload: { fixture: true, synthetic: true, fixtureId: 'mock-seongsu-cafe-1' },
  },
  {
    provider: 'mock-place',
    providerMode: 'mock',
    sourcePlaceId: 'mock-seongsu-shop-1',
    sourcePlaceIdKind: 'provider',
    name: '[MOCK] セレクトショップ',
    rawCategory: '쇼핑,유통>패션>편집샵',
    address: '서울특별시 성동구 성수동2가',
    roadAddress: '서울특별시 성동구 연무장길 10',
    longitude: 127.0559,
    latitude: 37.5428,
    rawPayload: { fixture: true, synthetic: true, fixtureId: 'mock-seongsu-shop-1' },
  },
  {
    provider: 'mock-place',
    providerMode: 'mock',
    sourcePlaceId: 'mock-seongsu-meat-1',
    sourcePlaceIdKind: 'provider',
    name: '[MOCK] 焼肉店',
    rawCategory: '음식점>한식>육류,고기요리',
    address: '서울특별시 성동구 성수동2가',
    roadAddress: '서울특별시 성동구 아차산로 20',
    longitude: 127.0591,
    latitude: 37.5442,
    rawPayload: { fixture: true, synthetic: true, fixtureId: 'mock-seongsu-meat-1' },
  },
  {
    provider: 'mock-place',
    providerMode: 'mock',
    sourcePlaceId: 'mock-seoul-park-1',
    sourcePlaceIdKind: 'provider',
    name: '[MOCK] ソウルの公園',
    rawCategory: '여행>명소>공원',
    address: '서울특별시 성동구 성수동1가',
    roadAddress: null,
    longitude: 127.0386,
    latitude: 37.5444,
    rawPayload: { fixture: true, synthetic: true, fixtureId: 'mock-seoul-park-1' },
  },
  {
    provider: 'mock-place',
    providerMode: 'mock',
    sourcePlaceId: 'mock-icn-t1',
    sourcePlaceIdKind: 'provider',
    name: '인천국제공항 제1여객터미널',
    rawCategory: '교통,수송>공항>국제공항',
    address: '인천광역시 중구 운서동 2840',
    roadAddress: '인천광역시 중구 공항로 271',
    longitude: 126.4505,
    latitude: 37.4485,
    rawPayload: { fixture: true, synthetic: true, fixtureId: 'mock-icn-t1', airport: true },
  },
  {
    provider: 'mock-place',
    providerMode: 'mock',
    sourcePlaceId: 'mock-icn-t2',
    sourcePlaceIdKind: 'provider',
    name: '인천국제공항 제2여객터미널',
    rawCategory: '교통,수송>공항>국제공항',
    address: '인천광역시 중구 운서동 2868',
    roadAddress: '인천광역시 중구 제2터미널대로 446',
    longitude: 126.4628,
    latitude: 37.4692,
    rawPayload: { fixture: true, synthetic: true, fixtureId: 'mock-icn-t2', airport: true },
  },
  {
    provider: 'mock-place',
    providerMode: 'mock',
    sourcePlaceId: 'mock-gmp',
    sourcePlaceIdKind: 'provider',
    name: '김포국제공항',
    rawCategory: '교통,수송>공항>국제공항',
    address: '서울특별시 강서구 방화동 886',
    roadAddress: '서울특별시 강서구 하늘길 112',
    longitude: 126.8013,
    latitude: 37.5585,
    rawPayload: { fixture: true, synthetic: true, fixtureId: 'mock-gmp', airport: true },
  },
  {
    provider: 'mock-place',
    providerMode: 'mock',
    sourcePlaceId: 'mock-hotel-mapo',
    sourcePlaceIdKind: 'provider',
    name: '롯데시티호텔 마포',
    rawCategory: '숙박>호텔',
    address: '서울특별시 마포구 공덕동 467',
    roadAddress: '서울특별시 마포구 마포대로 109',
    longitude: 126.9518,
    latitude: 37.5434,
    rawPayload: { fixture: true, synthetic: true, fixtureId: 'mock-hotel-mapo', hotel: true },
  },
  {
    provider: 'mock-place',
    providerMode: 'mock',
    sourcePlaceId: 'mock-hotel-seoul',
    sourcePlaceIdKind: 'provider',
    name: '롯데호텔 서울',
    rawCategory: '숙박>호텔',
    address: '서울특별시 중구 소공동 1',
    roadAddress: '서울특별시 중구 을지로 30',
    longitude: 126.9812,
    latitude: 37.5658,
    rawPayload: { fixture: true, synthetic: true, fixtureId: 'mock-hotel-seoul', hotel: true },
  },
  {
    provider: 'mock-place',
    providerMode: 'mock',
    sourcePlaceId: 'mock-shillastay-gongdeok',
    sourcePlaceIdKind: 'provider',
    name: '신라스테이 공덕',
    rawCategory: '숙박>호텔',
    address: '서울특별시 마포구 도화동 25-13',
    roadAddress: '서울특별시 마포구 마포대로 83',
    longitude: 126.9511,
    latitude: 37.5422,
    rawPayload: {
      fixture: true,
      synthetic: true,
      fixtureId: 'mock-shillastay-gongdeok',
      hotel: true,
    },
  },
  {
    provider: 'mock-place',
    providerMode: 'mock',
    sourcePlaceId: 'mock-shillastay-mapo',
    sourcePlaceIdKind: 'provider',
    name: '신라스테이 마포',
    rawCategory: '숙박>호텔',
    address: '서울특별시 마포구 도화동 17-22',
    roadAddress: '서울특별시 마포구 마포대로 92',
    longitude: 126.9507,
    latitude: 37.5426,
    rawPayload: { fixture: true, synthetic: true, fixtureId: 'mock-shillastay-mapo', hotel: true },
  },
  {
    provider: 'mock-place',
    providerMode: 'mock',
    sourcePlaceId: 'mock-shilla-seoul',
    sourcePlaceIdKind: 'provider',
    name: '서울신라호텔',
    rawCategory: '숙박>호텔',
    address: '서울특별시 중구 장충동2가 202',
    roadAddress: '서울특별시 중구 동호로 249',
    longitude: 127.0051,
    latitude: 37.5562,
    rawPayload: { fixture: true, synthetic: true, fixtureId: 'mock-shilla-seoul', hotel: true },
  },
  {
    provider: 'mock-place',
    providerMode: 'mock',
    sourcePlaceId: 'mock-ninetree-myeongdong',
    sourcePlaceIdKind: 'provider',
    name: '나인트리 프리미어 호텔 명동',
    rawCategory: '숙박>호텔',
    address: '서울특별시 중구 명동2가 83-5',
    roadAddress: '서울특별시 중구 명동길 61',
    longitude: 126.9858,
    latitude: 37.5638,
    rawPayload: {
      fixture: true,
      synthetic: true,
      fixtureId: 'mock-ninetree-myeongdong',
      hotel: true,
    },
  },
  {
    provider: 'mock-place',
    providerMode: 'mock',
    sourcePlaceId: 'mock-l7-hongdae',
    sourcePlaceIdKind: 'provider',
    name: 'L7 홍대 바이 롯데',
    rawCategory: '숙박>호텔',
    address: '서울특별시 마포구 동교동 160-5',
    roadAddress: '서울특별시 마포구 양화로 141',
    longitude: 126.9228,
    latitude: 37.5552,
    rawPayload: { fixture: true, synthetic: true, fixtureId: 'mock-l7-hongdae', hotel: true },
  },
  {
    provider: 'mock-place',
    providerMode: 'mock',
    sourcePlaceId: 'mock-westin-chosun',
    sourcePlaceIdKind: 'provider',
    name: '웨스틴 조선 서울',
    rawCategory: '숙박>호텔',
    address: '서울특별시 중구 소공동 87',
    roadAddress: '서울특별시 중구 소공로 106',
    longitude: 126.9798,
    latitude: 37.5645,
    rawPayload: { fixture: true, synthetic: true, fixtureId: 'mock-westin-chosun', hotel: true },
  },
];

@Injectable()
export class MockPlaceProvider implements PlaceProvider {
  readonly mode = 'mock' as const;
  readonly name = 'mock-place';

  async search(request: PlaceSearchRequest): Promise<PlaceSearchResponse> {
    const query = `${request.area} ${request.query}`.trim();
    const terms = request.query.toLowerCase().split(/\s+/);
    const matching = FIXTURES.filter((fixture) => {
      const searchable = `${fixture.name} ${fixture.rawCategory ?? ''}`.toLowerCase();
      return terms.some((term) => searchable.includes(term));
    });
    const places = (matching.length > 0 ? matching : FIXTURES).slice(0, request.limit ?? 5);
    return Promise.resolve({
      provider: this.name,
      providerMode: this.mode,
      query,
      places: places.map((place) => ({
        ...place,
        rawPayload: { ...place.rawPayload },
      })),
    });
  }
}
